### ISSUE TITLE
Missing basic policy

### ISSUE THREAD

**Issue by JelenaKovacc** [ertis-research/extended-api-for-eclipse-ditto#5]
Hi @juliarobles,

I installed the latest version (with Helm) of Opentwins and followed the Quickstart example. In one step, when we create a type, we need a basic policy. Can I generate it manually because I am missing one?

**Comment by den-dimas** [comment]
Hello, since you've completed this issue. I want to ask how did you solve it? Thanks in advance!

**Comment by juliarobles** [comment]
Hi @den-dimas,

In principle, the default installation should include the basic_policy. If it’s missing, it’s likely due to either an issue with the Eclipse Ditto Extended API not being able to access MongoDB, or the job responsible for creating the policy may have failed.

To fix this, you can try manually creating the policy using the Eclipse Ditto API. 

1. You'll need to check in your Kubernetes environment for the URL and port of the Ditto nginx service. If you're using Minikube, you must use minikube port-forward to expose the service.
2. Make a PUT to `/api/2/policies/default:basic_policy` with credentials for basic auth (by default username `ditto `and password `ditto`) and this body (I recommend using postman to this).
```
{
    "policyId": "default:basic_policy",
    "imports": {},
    "entries": {
        "DEFAULT": {
            "subjects": {
                "pre-authenticated:kafkaml-connection": {
                    "type": "Connection to KafkaML"
                },
                "pre-authenticated:hono-connection": {
                    "type": "Connection to Eclipse Hono"
                },
                "nginx:ditto": {
                    "type": "Ditto user authenticated via nginx"
                }
            },
            "resources": {
                "policy:/": {
                    "grant": [
                        "READ",
                        "WRITE"
                    ],
                    "revoke": []
                },
                "thing:/": {
                    "grant": [
                        "READ",
                        "WRITE"
                    ],
                    "revoke": []
                },
                "message:/": {
                    "grant": [
                        "READ",
                        "WRITE"
                    ],
                    "revoke": []
                }
            },
            "importable": "implicit"
        }
    }
}
```

If the issue was caused by the job failing, after this step you should be able to select the policy from the dropdown in the UI.

Alternatively, if that doesn’t solve it, you can create a type manually using the Ditto Extended API. 

1. Check in your Kubernetes environment for the URL and port of the Ditto extended API service.
2. Make a PUT to `/api/types/default:basic_type` with this body:
```
{
    "policyId": "default:basic_policy",
    "attributes": {},
    "features": {}
}
```

Once the type exists, you’ll be able to create twins in the UI based on it.

For now, this is the simplest solution, but you can also check if there are any errors in the logs of the Extended API or investigate why the job is failing in your environment — it depends on the root cause. Let us know if you need anything or have any questions :)

**Comment by den-dimas** [comment]
Hi @juliarobles, 

Thanks a lot for responding and give me some solutions. I think my problem lies on the extended API not being able to retrieve the policy data. Because when I try to get a request for ```basic_policy``` to the Ditto API, I get a response:

```bash
curl http://192.168.49.2:30525/api/2/policies/default:basic_policy -u ditto:ditto

{"policyId":"default:basic_policy","imports":{},"entries":{"DEFAULT":{"subjects":{"pre-authenticated:kafkaml-connection":{"type":"Connection to KafkaML"},"pre-authenticated:hono-connection":{"type":"Connection to Eclipse Hono"},"nginx:ditto":{"type":"Ditto user authenticated via nginx"}},"resources":{"policy:/":{"grant":["READ","WRITE"],"revoke":[]},"thing:/":{"grant":["READ","WRITE"],"revoke":[]},"message:/":{"grant":["READ","WRITE"],"revoke":[]}},"importable":"implicit"}}}
```

However, when I try to get the policies from the extended API, it returns an empty message:
```bash
curl 192.168.49.2:30526/api/policies

{
  "message": {}
}
```

I already tried the second solution (create a type manually using the Ditto Extended API) but the policy still not created. Do you recommend to just reinstall everything, or track the error logs even further?
